### PR TITLE
Fix product OrderItemController overwrite access level

### PR DESCRIPTION
**Pull request by wachterjohannes**
This PR fixes the access level of OrderItemController functions which has changed in https://github.com/Sylius/Sylius/commit/cd820cf79c227dd3f9ced64f60a2253047ccbd21

### CODE REVIEW

**Comment by Tyryshkinm** [comment]
@wachterjohannes 
Hi, I have a question for you. Did you manage to run this plugin?  Can you help me and tell me what I'm doing wrong, why I don't have a list of products in the product variant field that I want to add to the bundle when creating a new bundle? I tried to ask bundle's developer [here](https://github.com/BitBagCommerce/SyliusProductBundlePlugin/issues/2), but he hasn't answered yet.

**Comment by wachterjohannes** [comment]
@Tyryshkinm yes we managed it :) are you also inside the sylius slack-channel?

**Comment by Tyryshkinm** [comment]
@wachterjohannes 

> are you also inside the sylius slack-channel?
Now Yes, I just added to the sylius slack-channel)

> yes we managed it :)
Could you write a short instruction on how to install the plugin? Or let me describe what I did and maybe you can point me to mistakes?)

My steps:

1. Added 
```
BitBag\SyliusProductBundlePlugin\BitBagSyliusProductBundlePlugin::class => ['all' => true],
```
to bundles.php in /config dir.

2. Added 
```
bitbag_sylius_product_bundle_plugin:
    resource: "@BitBagSyliusProductBundlePlugin/Resources/config/routing.yml"
```
to routes.php in /config dir.

3. Created file "bitbag_sylius_product_bundle_plugin.yml" with
```
imports:
    - { resource: "@BitBagSyliusProductBundlePlugin/Resources/config/config.yml" }
```
in /config/packages dir.

4. Added path to repository for product_variant of sylius_product in _sylius.yaml in /config/packages dir:
```
sylius_product:
    resources:
        product:
            classes:
                model: App\Entity\Product\Product
            translation:
                classes:
                    model: App\Entity\Product\ProductTranslation
        product_variant:
            classes:
                repository: BitBag\SyliusProductBundlePlugin\Repository\ProductVariantRepository
                model: App\Entity\Product\ProductVariant
            translation:
```

5. Overrided Product Entity with
```
<?php

declare(strict_types=1);

namespace App\Entity\Product;

use BitBag\SyliusProductBundlePlugin\Entity\ProductBundlesAwareTrait;
use BitBag\SyliusProductBundlePlugin\Entity\ProductInterface;
use Sylius\Component\Core\Model\Product as BaseProduct;
use Doctrine\ORM\Mapping as ORM;
use Sylius\Component\Product\Model\ProductTranslationInterface;

/**
 * Class Product
 * @package App\Entity\Product
 * @ORM\Entity
 * @ORM\MappedSuperclass
 * @ORM\Table(name="sylius_product")
 */
class Product extends BaseProduct implements ProductInterface
{
    use ProductBundlesAwareTrait;

    protected function createTranslation(): ProductTranslationInterface
    {
        return new ProductTranslation();
    }
}
```

6. Generated migration via `php bin/console doctrine:migrations:diff`.
7. Applied new migration via `php bin/console doctrine:migrations:migrate`.
8. Overrided templates from tests dir of this plugin.

Hmm, i think it's all...and now, when I want to create a product bundle, a simple product is created and the records in the tables with the prefix bitbag are not added in database, maybe you know what could be the problem?)

**Comment by Tyryshkinm** [comment]
@wachterjohannes 
Yes, this solved my problem, thank you so much! I plan to write a small installation guide based on our communication, perhaps this will be useful to someone. Thank you again, you helped me a lot)

**Comment by macintoshplus** [comment]
Hi,

Thanks for this PR and small doc. This bundle work !

**Comment by czechmarcin** [comment]
No more workarounds, it's fixed on master ;)
https://github.com/BitBagCommerce/SyliusProductBundlePlugin/pull/4

**Comment by damonsson** [comment]
Solution in #4

**Pull request closed without merging**
